### ISSUE TITLE
click() not working on HTMLAnchorElement

### ISSUE THREAD

**Issue by steve-mills** [ampproject/worker-dom#1009] opened 2020-11-23 02:10 UTC
Hi guys,
The HTMLElement.click() doesn't seem to be working if I get an element from the existing DOM with getElementById.
Do I need to dynamically add an element to the Document get this to work? 

Here's an example of what I have tried. The setAttribute method works fine when used like this, .click() doesn't.

document.querySelectorAll('.button').addEventListener('click', clicker);
const clicker = function(event){ 
 let ev = event.target.id;
let anchor = ev + '.html';
 let evB = ev + 'Button';
 let evBL = document.getElementById(evB);
 evBL.click();
   };

Thanks for your help,
Kind Regards

**Comment by samouri** [comment] 2020-11-23 06:18
@steve-mills: do you know if the `evBL` click handler is called or not? Also, what type of element is `evBL`?
Calling `.click()` on anchor tags (`<a>`) is currently broken.

**Comment by steve-mills** [comment] 2020-11-23 12:24
Hi Jake,
Thanks heaps for your response. 
Sorry evBL is an anchor tag (I'm not a developer and I'm new to git). 
event.target.id is a hex shaped SVG path that triggers an anchor when clicked. I should have commented
. Is there a work around to trigger a href?

**Comment by samouri** [comment] 2020-11-23 14:45
Ok! Glad to hear it is indeed an anchor.
I don't think fixing it is at the top of anyone's priority list right now.
We are of course open to pull requests!

**Comment by samouri** [comment] 2021-03-23 15:01
Closing this as a dupe of https://github.com/ampproject/worker-dom/issues/917

**Closed by samouri** 2021-03-23 15:01 UTC
